// Word lists per topic and language.
// Entries are comma-separated; "|" separates accepted alternative names for the same thing
// (the first one is the display name). Saying any alias uses up the whole entry.
window.TOPICS = [
  {
    id: 'animals',
    en: 'Animals', am: 'እንስሳት',
    words: {
      en: `Aardvark, Albatross, Alligator, Alpaca, Anaconda, Ant, Anteater, Antelope, Ape, Armadillo,
        Baboon, Badger, Bat, Bear, Beaver, Bee, Beetle, Bison, Boar, Buffalo, Bull, Butterfly,
        Camel, Canary, Caribou, Cat, Caterpillar, Cheetah, Chicken, Chimpanzee|Chimp, Chinchilla, Chipmunk, Cobra, Cockroach, Cougar, Cow, Coyote, Crab, Crane, Cricket, Crocodile, Crow,
        Deer, Dingo, Dog, Dolphin, Donkey, Dove, Dragonfly, Duck,
        Eagle, Eel, Elephant, Elk, Emu,
        Falcon, Ferret, Finch, Fish, Flamingo, Fly, Fox, Frog,
        Gazelle, Gecko, Gerbil, Gibbon, Giraffe, Gnu, Goat, Goldfish, Goose, Gorilla, Grasshopper, Guinea pig, Gull,
        Hamster, Hare, Hawk, Hedgehog, Heron, Hippo|Hippopotamus, Horse, Hummingbird, Hyena,
        Ibex, Ibis, Iguana, Impala,
        Jackal, Jaguar, Jellyfish,
        Kangaroo, Kingfisher, Kiwi, Koala, Komodo dragon,
        Ladybug|Ladybird, Lamb, Lemur, Leopard, Lion, Lizard, Llama, Lobster, Lynx,
        Macaw, Magpie, Mammoth, Manatee, Meerkat, Mole, Mongoose, Monkey, Moose, Mosquito, Moth, Mouse, Mule,
        Narwhal, Newt, Nightingale,
        Ocelot, Octopus, Opossum, Orangutan, Orca, Ostrich, Otter, Owl, Ox, Oyster,
        Panda, Panther, Parrot, Peacock, Pelican, Penguin, Pheasant, Pig, Pigeon, Piranha, Platypus, Polar bear, Pony, Porcupine, Possum, Puffin, Puma, Python,
        Quail, Quokka, Quetzal,
        Rabbit, Raccoon, Ram, Rat, Raven, Reindeer, Rhino|Rhinoceros, Robin, Rooster,
        Salamander, Salmon, Scorpion, Seahorse, Seal, Shark, Sheep, Shrimp, Skunk, Sloth, Snail, Snake, Sparrow, Spider, Squid, Squirrel, Starfish, Stingray, Stork, Swallow, Swan,
        Tapir, Tarantula, Termite, Tiger, Toad, Tortoise, Toucan, Trout, Tuna, Turkey, Turtle,
        Uakari, Urchin|Sea urchin, Urial,
        Vicuna, Viper, Vole, Vulture,
        Walrus, Warthog, Wasp, Weasel, Whale, Wildebeest, Wolf, Wombat, Woodpecker, Worm,
        Xerus,
        Yak, Yellowjacket,
        Zebra, Zebu`,
      am: `አንበሳ, ነብር, ዝሆን, ቀጭኔ, ጅብ, ቀበሮ, ውሻ, ድመት, ፈረስ, አህያ, በቅሎ, ላም, በሬ, በግ, ፍየል, ዶሮ, ግመል, ጦጣ, ዝንጀሮ, አይጥ,
        እባብ, አሳ|ዓሣ, ንስር, ጉማሬ, አውራሪስ, አዞ, ኤሊ, ጥንቸል, ሚዳቋ, አጋዘን, ቁራ, እርግብ, ንብ, ዝንብ, ጉንዳን, ቢራቢሮ, እንቁራሪት,
        ጅግራ, ሰጎን, ጉጉት, ዋልያ, ቆቅ, ጃርት, አሞራ, ዳክዬ, ተኩላ, ዓሣ ነባሪ|አሳ ነባሪ, ቁንጫ, ትንኝ, ሸረሪት, ጊንጥ, ቀንድ አውጣ,
        ፌንጣ, አንበጣ, ምስጥ, ኮርማ, ጥጃ, ግልገል, ጫጩት, ቡችላ, ድኩላ, ከርከሮ, አሳማ, ጎሽ, የሜዳ አህያ|ሜዳ አህያ, ቀይ ቀበሮ,
        ጭላዳ, ጉሬዛ, ወፍ, ድንቢጥ, ሽመላ, ጭልፊት, ቅማል, ትል, ዘንዶ, ጥርኝ, ፔንግዊን, ካንጋሮ, ፓንዳ, ዶልፊን, ሻርክ, ጉማሬ, ፍየል`
    }
  },
  {
    id: 'fruits',
    en: 'Fruits & Vegetables', am: 'ፍራፍሬና አትክልት',
    words: {
      en: `Apple, Apricot, Artichoke, Arugula, Asparagus, Avocado,
        Banana, Beet|Beetroot, Bell pepper, Blackberry, Blueberry, Bok choy, Breadfruit, Broccoli, Brussels sprout,
        Cabbage, Cantaloupe, Carrot, Cauliflower, Celery, Chard, Cherry, Chili|Chilli, Clementine, Coconut, Collard, Corn, Cranberry, Cucumber, Currant,
        Date, Dragon fruit, Durian,
        Eggplant|Aubergine, Elderberry, Endive,
        Fennel, Fig,
        Garlic, Ginger, Gooseberry, Gourd, Grape, Grapefruit, Green bean, Guava,
        Honeydew, Horseradish, Huckleberry,
        Iceberg lettuce,
        Jackfruit, Jalapeno, Jicama,
        Kale, Kiwi, Kohlrabi, Kumquat,
        Leek, Lemon, Lettuce, Lime, Loquat, Lychee,
        Mandarin, Mango, Melon, Mulberry, Mushroom,
        Nectarine,
        Okra, Olive, Onion, Orange,
        Papaya, Parsnip, Passion fruit, Pea, Peach, Pear, Pepper, Persimmon, Pineapple, Plantain, Plum, Pomegranate, Potato, Pumpkin,
        Quince,
        Radicchio, Radish, Raisin, Raspberry, Rhubarb, Rutabaga,
        Shallot, Soursop, Spinach, Squash, Starfruit, Strawberry, Sweet potato,
        Tamarind, Tangerine, Tomato, Turnip,
        Ugli fruit,
        Watercress, Watermelon,
        Xigua,
        Yam, Yuzu,
        Zucchini|Courgette`,
      am: `ሙዝ, ብርቱካን|ብርቱካን, ሎሚ, ማንጎ, አቮካዶ|አቦካዶ, ፓፓያ, አናናስ, ወይን, ፖም, ኮክ, ዘይቱን, ቲማቲም, ሽንኩርት, ነጭ ሽንኩርት,
        ድንች, ስኳር ድንች, ካሮት, ጎመን, ቃሪያ, በርበሬ, ሰላጣ, ዱባ, ቆስጣ, ጥቅል ጎመን, ቀይ ስር, ሸንኮራ አገዳ|ሸንኮራ, እንጆሪ, ትርንጎ,
        መንደሪን, በለስ, ቴምር, ሀብሀብ|ሐብሐብ, ዘይቱና|ጉዋቫ, ኪያር, ፎሶሊያ|ፋሶሊያ, አተር, ባቄላ, ምስር, ሽምብራ, በቆሎ, ዝንጅብል,
        ቦሎቄ, እንሰት, ጎደሬ, ብሮኮሊ, አበባ ጎመን, ኮኮናት, ኪዊ, ሮማን, ጓያ, ቀይ ሽንኩርት, ቃሪያ, ዱባ`
    }
  },
  {
    id: 'food',
    en: 'Food & Drinks', am: 'ምግብና መጠጥ',
    words: {
      en: `Ambasha, Apple pie, Arepa,
        Bacon, Bagel, Baguette, Baklava, Barbecue, Biryani, Biscuit, Bread, Brioche, Brownie, Bun, Buna, Burger|Hamburger, Burrito, Butter,
        Cake, Candy, Cappuccino, Caramel, Cereal, Cheese, Cheesecake, Chips|Crisps, Chocolate, Coffee, Cola|Coke, Cookie, Couscous, Crepe, Croissant, Cupcake, Curry, Custard,
        Donut|Doughnut, Doro wat|Doro wot, Dumpling,
        Eclair, Egg, Eggnog, Empanada, Enchilada, Espresso,
        Falafel, Firfir, Flapjack, Focaccia, Fries|French fries, Fudge,
        Garlic bread, Gelato, Genfo, Gnocchi, Granola, Gravy, Guacamole,
        Ham, Hash brown, Honey, Hot chocolate, Hot dog, Hummus,
        Ice cream, Icing, Injera,
        Jam, Jelly, Jerky, Jollof|Jollof rice, Juice,
        Kebab, Kefir, Ketchup, Kimchi, Kitfo, Kolo, Kombucha,
        Lasagna|Lasagne, Latte, Lemonade, Lollipop,
        Macaroni|Mac and cheese, Marmalade, Mayonnaise|Mayo, Meatball, Milk, Milkshake, Mocha, Muffin, Mustard,
        Naan, Nachos, Noodles, Nougat, Nuggets,
        Oatmeal, Omelette|Omelet, Onion rings,
        Paella, Pancake, Pasta, Pastry, Pho, Pie, Pilaf, Pizza, Popcorn, Porridge, Pretzel, Pudding,
        Quesadilla, Quiche, Quinoa,
        Ramen, Ratatouille, Ravioli, Rice, Risotto,
        Salad, Salsa, Samosa|Sambusa, Sandwich, Sausage, Shiro, Smoothie, Soda, Sorbet, Soup, Spaghetti, Steak, Stew, Sushi,
        Taco, Tea, Tej, Tella, Tempura, Tibs, Toast, Tofu, Tortilla,
        Udon,
        Vanilla, Vinegar,
        Waffle, Water, Wine, Wrap,
        Xiaolongbao,
        Yogurt|Yoghurt, Yorkshire pudding,
        Ziti`,
      am: `እንጀራ, ዶሮ ወጥ, ሽሮ, ክትፎ, ጥብስ, ዳቦ, ቡና, ሻይ, ወተት, ጠላ, ጠጅ, ቅቤ, ማር, ጨው, ስኳር, አይብ, ቂጣ, ቆሎ, ፍርፍር, ጭኮ,
        ገንፎ, ዱለት, ቋንጣ, ቦርዴ, ቢራ, ውሃ|ውሀ, ጭማቂ, እንቁላል, ስጋ|ሥጋ, ሩዝ, ፓስታ, በየአይነቱ|በያይነቱ, ሚጥሚጣ, አዋዜ, ጎረድ ጎረድ,
        ዱቄት, ቆጮ, ቡላ, ምስር ወጥ, ቅቅል, ቀይ ወጥ, አልጫ, ጨጨብሳ, ዳቦ ቆሎ, ሳምቡሳ, ሾርባ, ፒዛ, በርገር, ኬክ, ብስኩት, ከረሜላ,
        ቸኮሌት, ማኪያቶ, ለስላሳ, አረቄ, ዘይት, ቅንጬ, ጥሬ ስጋ, ፉል, አምባሻ, ቋንጣ ፍርፍር, ዳጣ, ሽሮ ፈሰስ, ጎመን`
    }
  },
  {
    id: 'countries',
    en: 'Countries', am: 'አገሮች',
    words: {
      en: `Afghanistan, Albania, Algeria, Andorra, Angola, Antigua and Barbuda|Antigua, Argentina, Armenia, Australia, Austria, Azerbaijan,
        Bahamas, Bahrain, Bangladesh, Barbados, Belarus, Belgium, Belize, Benin, Bhutan, Bolivia, Bosnia and Herzegovina|Bosnia, Botswana, Brazil, Brunei, Bulgaria, Burkina Faso, Burundi,
        Cambodia, Cameroon, Canada, Cape Verde|Cabo Verde, Central African Republic, Chad, Chile, China, Colombia, Comoros, Congo|Democratic Republic of the Congo|DRC, Costa Rica, Croatia, Cuba, Cyprus, Czech Republic|Czechia,
        Denmark, Djibouti, Dominica, Dominican Republic,
        Ecuador, Egypt, El Salvador|Salvador, England, Equatorial Guinea, Eritrea, Estonia, Eswatini|Swaziland, Ethiopia,
        Fiji, Finland, France,
        Gabon, Gambia, Georgia, Germany, Ghana, Greece, Grenada, Guatemala, Guinea, Guinea-Bissau, Guyana,
        Haiti, Honduras, Hungary,
        Iceland, India, Indonesia, Iran, Iraq, Ireland, Israel, Italy, Ivory Coast|Cote d'Ivoire,
        Jamaica, Japan, Jordan,
        Kazakhstan, Kenya, Kiribati, Kosovo, Kuwait, Kyrgyzstan,
        Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg,
        Madagascar, Malawi, Malaysia, Maldives, Mali, Malta, Marshall Islands, Mauritania, Mauritius, Mexico, Micronesia, Moldova, Monaco, Mongolia, Montenegro, Morocco, Mozambique, Myanmar|Burma,
        Namibia, Nauru, Nepal, Netherlands|Holland, New Zealand, Nicaragua, Niger, Nigeria, North Korea, North Macedonia|Macedonia, Norway,
        Oman,
        Pakistan, Palau, Palestine, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal,
        Qatar,
        Romania, Russia, Rwanda,
        Saint Lucia, Samoa, San Marino, Saudi Arabia, Scotland, Senegal, Serbia, Seychelles, Sierra Leone, Singapore, Slovakia, Slovenia, Solomon Islands, Somalia, South Africa, South Korea|Korea, South Sudan, Spain, Sri Lanka, Sudan, Suriname, Sweden, Switzerland, Syria,
        Taiwan, Tajikistan, Tanzania, Thailand, Togo, Tonga, Trinidad and Tobago|Trinidad, Tunisia, Turkey|Turkiye, Turkmenistan, Tuvalu,
        Uganda, Ukraine, United Arab Emirates|UAE|Emirates, United Kingdom|UK|Britain|Great Britain, United States|USA|America|United States of America, Uruguay, Uzbekistan,
        Vanuatu, Vatican|Vatican City, Venezuela, Vietnam,
        Wales,
        Yemen,
        Zambia, Zimbabwe`,
      am: `ኢትዮጵያ, ኬንያ, ሱዳን, ደቡብ ሱዳን, ግብፅ|ግብጽ, ሶማሊያ, ጅቡቲ|ጂቡቲ, ኤርትራ, ናይጄሪያ, ጋና, ቻይና, ጃፓን, ህንድ|ሕንድ, ሩሲያ,
        ጀርመን, ፈረንሳይ, ጣሊያን|ኢጣሊያ, እንግሊዝ|ብሪታንያ, አሜሪካ, ካናዳ, ብራዚል, ሜክሲኮ, ስፔን, ቱርክ, ኢራን, ኢራቅ, እስራኤል,
        ሳዑዲ አረቢያ|ሳውዲ አረቢያ|ሳዑዲ, የመን, ኡጋንዳ, ታንዛኒያ, ሩዋንዳ, ቡሩንዲ, ኮንጎ, ደቡብ አፍሪካ, ሞሮኮ, አልጄሪያ, ቱኒዚያ|ቱኒዝያ,
        ሊቢያ, ግሪክ, ፖርቱጋል, ኔዘርላንድ|ሆላንድ, ቤልጂየም, ስዊድን, ኖርዌይ, ዴንማርክ, ፊንላንድ, ፖላንድ, ዩክሬን, አውስትራሊያ,
        ደቡብ ኮሪያ|ኮሪያ, ሰሜን ኮሪያ, ቬትናም, ታይላንድ, ኢንዶኔዥያ|ኢንዶኔዢያ, ፓኪስታን, አፍጋኒስታን, ኩባ, አርጀንቲና, ቺሊ, ኮሎምቢያ,
        ፔሩ, ቬንዙዌላ, ማሊ, ሴኔጋል, ካሜሩን, ዚምባብዌ, ዛምቢያ, ሞዛምቢክ, ማዳጋስካር, አንጎላ, ናሚቢያ, ቦትስዋና, ቻድ, ኒጀር,
        ሶሪያ, ዮርዳኖስ, ሊባኖስ, ኳታር, ኩዌት, ኦማን, ስዊዘርላንድ, ኦስትሪያ, ሀንጋሪ, አየርላንድ, ስኮትላንድ, ኒውዚላንድ|ኒው ዚላንድ,
        ጃማይካ, ሄይቲ, ፊሊፒንስ, ማሌዢያ|ማሌዥያ, ሲንጋፖር, ባንግላዲሽ, ኔፓል, ስሪላንካ|ሲሪላንካ, ኢኳዶር, ቦሊቪያ, ፓራጓይ, ኡራጓይ,
        ኡዝቤኪስታን, ካዛኪስታን, ማላዊ, ላይቤሪያ, ሴራሊዮን, ጊኒ, ቶጎ, ቤኒን, ጋቦን, ሞሪታኒያ, ሲሼልስ, ሞሪሸስ, ሌሶቶ,
        ኤስዋቲኒ|ስዋዚላንድ, ቼክ, ስሎቫኪያ, ሮማኒያ, ቡልጋሪያ, ሰርቢያ, ክሮኤሺያ, አልባኒያ, አርሜኒያ, ጆርጂያ, አዘርባጃን, ቆጵሮስ,
        ማልታ, አይስላንድ, ሉክሰምበርግ, ሞናኮ, ቫቲካን, ታይዋን, ሞንጎሊያ, ካምቦዲያ, ምያንማር|በርማ, ላኦስ, ባህሬን, ፍልስጤም`
    }
  },
  {
    id: 'cities',
    en: 'Cities', am: 'ከተሞች',
    words: {
      en: `Abu Dhabi, Accra, Adama, Addis Ababa, Adelaide, Algiers, Amman, Amsterdam, Ankara, Antwerp, Asmara, Athens, Atlanta, Auckland, Axum|Aksum,
        Baghdad, Bahir Dar, Baku, Bangalore|Bengaluru, Bangkok, Barcelona, Beijing, Beirut, Belgrade, Berlin, Bern, Birmingham, Bogota, Boston, Brasilia, Brisbane, Bristol, Brussels, Bucharest, Budapest, Buenos Aires,
        Cairo, Calgary, Canberra, Cape Town, Caracas, Casablanca, Chennai, Chicago, Copenhagen,
        Dakar, Dallas, Damascus, Dar es Salaam, Delhi|New Delhi, Denver, Dessie, Detroit, Dhaka, Dire Dawa, Doha, Dubai, Dublin, Durban,
        Edinburgh,
        Florence, Frankfurt,
        Geneva, Glasgow, Gondar, Guangzhou,
        Hamburg, Hanoi, Harar, Havana, Hawassa|Awasa, Helsinki, Hong Kong, Honolulu, Houston, Hyderabad,
        Ibadan, Istanbul,
        Jakarta, Jeddah, Jerusalem, Jimma, Johannesburg, Juba,
        Kabul, Kampala, Kano, Karachi, Kathmandu, Khartoum, Kigali, Kinshasa, Kolkata, Kyiv|Kiev, Kyoto,
        Lagos, Lahore, Lalibela, Las Vegas, Lima, Lisbon, Liverpool, London, Los Angeles, Luanda, Lyon,
        Madrid, Malaga, Manchester, Manila, Marrakesh|Marrakech, Marseille, Mecca, Medina, Mekelle, Melbourne, Mexico City, Miami, Milan, Minneapolis, Mogadishu, Mombasa, Montreal, Moscow, Mumbai, Munich,
        Nairobi, Naples, New Orleans, New York, Nice,
        Osaka, Oslo, Ottawa, Ouagadougou, Oxford,
        Paris, Perth, Philadelphia, Phoenix, Prague, Pretoria,
        Quebec, Quito,
        Rabat, Reykjavik, Riga, Rio de Janeiro|Rio, Riyadh, Rome, Rotterdam,
        San Diego, San Francisco, Santiago, Sao Paulo, Seattle, Seoul, Seville, Shanghai, Singapore, Sofia, Stockholm, Sydney,
        Taipei, Tallinn, Tashkent, Tehran, Tel Aviv, Tokyo, Toronto, Tripoli, Tunis, Turin,
        Ulaanbaatar, Utrecht,
        Valencia, Vancouver, Venice, Vienna, Vilnius,
        Warsaw, Washington, Wellington, Windhoek,
        Xian,
        Yangon, Yaounde, Yerevan, Yokohama,
        Zagreb, Zanzibar, Zurich`,
      am: `አዲስ አበባ, ጎንደር, ባህር ዳር|ባሕር ዳር, መቀሌ, ሀዋሳ|አዋሳ, አዳማ|ናዝሬት, ድሬዳዋ|ድሬ ዳዋ, ጅማ, ደሴ, ሐረር, አክሱም, ላሊበላ,
        ደብረ ብርሃን, ደብረ ማርቆስ, ቢሾፍቱ|ደብረ ዘይት, አርባ ምንጭ, ነቀምት|ነቀምቴ, ጋምቤላ, አሶሳ, ሰመራ, ጅጅጋ|ጅግጅጋ, ሆሳዕና,
        ወላይታ ሶዶ|ሶዶ, ዲላ, ሻሸመኔ, ቡታጅራ, ወልቂጤ, ደብረ ታቦር, ወልዲያ, ኮምቦልቻ, ሞጆ, ሆለታ, አምቦ, ጊምቢ, ሚዛን ተፈሪ, ቦንጋ,
        ጎባ, ሮቤ, ነገሌ, ያቤሎ, ሞያሌ, አዲግራት, ሽሬ, ሁመራ, ፍቼ, ዝዋይ|ባቱ, አሰላ, መቱ, ቴፒ, ደምቢ ዶሎ, ጭሮ, ደባርቅ, ደብረ ሲና,
        ሰበታ, ቡራዩ, ለገጣፎ, ዱከም, መተሐራ, አዋሽ, አድዋ|ዓድዋ, ውቅሮ, ማይጨው, ኮረም, አላማጣ, ቆቦ, ፍኖተ ሰላም, ዳንግላ, እንጅባራ,
        ቻግኒ, ሞጣ, ደጀን, ሸዋ ሮቢት, አንኮበር, ጂንካ|ጅንካ, ኮንሶ, ሳውላ, ዱራሜ, ወራቤ, ጎሬ, በደሌ, አጋሮ, ሻምቡ, ነጆ, ወሊሶ, ጊንጪ,
        አዲስ አለም, ሱሉልታ, ናይሮቢ, ካይሮ, ለንደን, ፓሪስ, ሮም|ሮማ, ዋሽንግተን, ኒው ዮርክ|ኒውዮርክ, ዱባይ, ጅዳ, ካርቱም, ሞስኮ,
        ቤጂንግ, ቶኪዮ, በርሊን, ማድሪድ, ሎስ አንጀለስ, ቶሮንቶ, ጆሃንስበርግ, ኪጋሊ, ካምፓላ, ዳሬ ሰላም, ሞቃዲሾ, አስመራ,
        ኢየሩሳሌም|እየሩሳሌም, ሪያድ, ኢስታንቡል, ሌጎስ, አክራ, ዳካር, ቺካጎ, ዳላስ, አትላንታ, ሲያትል, ዴንቨር, ቦስተን, ቤይሩት,
        ዶሃ, አቡዳቢ, ቬኒስ, ሚላን, ጄኔቫ, ብራሰልስ, አምስተርዳም, ስቶክሆልም, ኦስሎ, ኮፐንሃገን, ሲድኒ, ሜልቦርን, ሙምባይ,
        ዴልሂ|ኒው ዴልሂ, ካራቺ, ሻንጋይ, ሴኡል, ባንኮክ, ሃቫና, ሪዮ ዴ ጄኔሮ, ሳኦ ፓውሎ, ቦነስ አይረስ, ሜክሲኮ ሲቲ, ኦታዋ,
        ሞንትሪያል, ቫንኩቨር`
    }
  },
  {
    id: 'jobs',
    en: 'Jobs', am: 'ሙያዎች',
    words: {
      en: `Accountant, Actor|Actress, Architect, Artist, Astronaut, Athlete, Author,
        Baker, Banker, Barber, Barista, Bricklayer, Builder, Butcher,
        Carpenter, Cashier, Chef, Cleaner, Coach, Cook,
        Dancer, Dentist, Designer, Detective, Developer, Dietitian, Diplomat, Doctor, Driver,
        Economist, Editor, Electrician, Engineer, Entrepreneur,
        Farmer, Firefighter, Fisherman, Florist,
        Gardener, Geologist, Guard, Guide,
        Hairdresser, Historian,
        Illustrator, Interpreter, Inventor, Investor,
        Janitor, Jeweler|Jeweller, Journalist, Judge,
        Kindergarten teacher,
        Lawyer, Lecturer, Librarian, Lifeguard, Locksmith,
        Magician, Manager, Mechanic, Midwife, Miner, Model, Musician,
        Nanny, Navigator, Novelist, Nurse,
        Oceanographer, Officer, Optician, Optometrist,
        Painter, Pharmacist, Photographer, Physicist, Pilot, Plumber, Poet, Police officer|Policeman|Policewoman, Politician, Postman|Mail carrier, Priest, Professor, Programmer, Psychologist,
        Quantity surveyor,
        Receptionist, Reporter,
        Sailor, Salesman|Salesperson, Scientist, Secretary, Shepherd, Singer, Soldier, Surgeon,
        Tailor, Teacher, Technician, Therapist, Translator, Tutor,
        Umpire, Underwriter, Usher,
        Veterinarian|Vet,
        Waiter|Waitress, Welder, Writer,
        X-ray technician,
        Yoga instructor, YouTuber,
        Zookeeper, Zoologist`,
      am: `ሐኪም|ዶክተር, መምህር|አስተማሪ, ነርስ, ሹፌር|ሾፌር, ገበሬ, ነጋዴ, አናጺ|አናጢ, ግንበኛ, ዳኛ, ጠበቃ, ፖሊስ, ወታደር, አብራሪ|ፓይለት,
        መሐንዲስ|ኢንጂነር, ጋዜጠኛ, ዘፋኝ|ድምፃዊ, ሰዓሊ, ጸሐፊ, ገጣሚ, ምግብ አብሳይ|ሼፍ, ፀጉር አስተካካይ, ልብስ ሰፊ, ቀጥቃጭ, ሸክላ ሠሪ,
        እረኛ, አሳ አጥማጅ, ሂሳብ ሹም|አካውንታንት, ፋርማሲስት, ሳይንቲስት, ፕሮግራመር, ተዋናይ, ካህን, ቄስ, ጠባቂ|ዘበኛ, አስተናጋጅ,
        ሻጭ, ሸማኔ, ሚኒስትር, ፕሬዚዳንት, ዲፕሎማት, አትሌት|ሯጭ, ኳስ ተጫዋች|እግር ኳስ ተጫዋች, አሰልጣኝ, ሞግዚት, ቧንቧ ሰራተኛ,
        ኤሌክትሪሽያን, መካኒክ, ገንዘብ ተቀባይ, ደላላ, ሊስትሮ, ጫማ ሰፊ, ወጌሻ, አዋላጅ, ዳቦ ጋጋሪ, ስጋ ቆራጭ, ፎቶ አንሺ|ፎቶግራፈር,
        ተርጓሚ, ዲዛይነር, ሞዴል, ኮሜዲያን, ዳንሰኛ|ተወዛዋዥ, ሙዚቀኛ, ተመራማሪ, ፕሮፌሰር, ኢኮኖሚስት, ዳኛ`
    }
  }
];
